# Generated by Django 4.1.7 on 2023-06-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akash', '0004_alter_learning_discription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
