# Generated by Django 4.1.7 on 2023-06-07 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akash', '0008_usercourse_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
